### ISSUE TITLE
Example contains a missing `path` for the `Get()` decorator - causes a type error

### ISSUE THREAD

**Issue by joshuaja-tangelo** [gaurishhs/elysia-decorators#2]
Example should be updated to add a `path` string as an argument to the `Get()` decorator to avoid a type error:

```
import { Controller, Get, decorators } from "elysia-decorators";
import { Elysia } from "elysia";

// /users prefix
@Controller("/users/")
class UsersController {
  @Get("")
  index() {
    return "Hello World";
  }
}

const app = new Elysia();

app.use(
  decorators({
    controllers: [UsersController],
  })
);

app.listen(3000);
```

Additionally, the user will need to make sure to set `"experimentalDecorators": true,` in their `tsconfig.json` `compilerOptions` object to avoid a type error on the `Controller()` decorator argument.

**Comment by gaurishhs** [comment]
Hi! sorry for the late response. Please open a PR

**Comment by gaurishhs** [comment]
Can you open a PR for this?

**Comment by gaurishhs** [comment]
Fixed
