### ISSUE TITLE
Unable to resolve signature of class decorator when called as an expression.

### ISSUE THREAD

**Issue by delikesance** [gaurishhs/elysia-decorators#3]
Unable to resolve signature of class decorator when called as an expression.
  The runtime will invoke the decorator with 2 arguments, but the decorator expects 1.
  
The following code give me the previous error :

```typescript
@Controller("/users/")
class UsersController {
  @Get("")
  index() {
    return "Hello World";
  }
}
```

**Comment by delikesance** [comment]
Fixed by uncommenting this line on the tsconfig :
    "experimentalDecorators": true,                   /* Enable experimental support for TC39 stage 2 draft decorators. */

**Comment by gaurishhs** [comment]
yeah, i probably need to mention about this in the readme
