### ISSUE TITLE
Missing dependency with latest version

### ISSUE THREAD

**Issue by awallat** [gaurishhs/elysia-decorators#4]
Using the latest version of bun (1.0.21) and elysia, I cannot use the decorators anymore. The following error appears:

```
$ bun build --target bun src/index.ts --outdir ./dist
       return allDirs.concat(require('glob').sync(path.normalize(dir)));
                                           ^
error: Could not resolve: "glob". Maybe you need to "bun install"?
```

After adding "glob" to my package.json. It's working again.

**Comment by gaurishhs** [comment]
Yes, that's the intended behaviour. I probably didn't mention it in the readme but i did it here https://github.com/gaurishhs/elysia-decorators/blob/main/demo/index.ts#L2

**Comment by gaurishhs** [comment]
But i think i should migrate to `Bun.Glob`

**Comment by awallat** [comment]
Thanks for the information. Using `Bun.Glob` sounds like a good idea!
